### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by aerograf** [XoopsModules25x/contact#11]
XOOPS 2.5.9
PHP 7.0.17
-----------
An error occurs when updating:
Error: Class 'ContentConfigurator' not found
Error: Class 'ContentConfigurator' not found in the file /modules/contact/include/onupdate.php line 141

**Comment by aerograf** [comment]
The access rights to the guest module are not set. Through groups, etc.

**Comment by mambax7** [comment]
https://github.com/XoopsModules25x/contact/pull/12
